// F&O eligible stocks with Dhan Security IDs (NSE Cash segment)
// SecurityID sourced from Dhan scrip master: SEM_INSTRUMENT_NAME=EQUITY, SEM_EXM_EXCH_ID=NSE
export const FO_STOCKS = [
  { symbol: "RELIANCE",       securityId: "2885",  name: "Reliance Industries",      sector: "Energy" },
  { symbol: "HDFCBANK",       securityId: "1333",  name: "HDFC Bank",                sector: "Banking" },
  { symbol: "ICICIBANK",      securityId: "4963",  name: "ICICI Bank",               sector: "Banking" },
  { symbol: "INFY",           securityId: "1594",  name: "Infosys",                  sector: "IT" },
  { symbol: "TCS",            securityId: "11536", name: "TCS",                      sector: "IT" },
  { symbol: "KOTAKBANK",      securityId: "1922",  name: "Kotak Mahindra Bank",      sector: "Banking" },
  { symbol: "LT",             securityId: "11483", name: "Larsen & Toubro",          sector: "Capital Goods" },
  { symbol: "HINDUNILVR",     securityId: "1558",  name: "Hindustan Unilever",       sector: "FMCG" },
  { symbol: "AXISBANK",       securityId: "5900",  name: "Axis Bank",                sector: "Banking" },
  { symbol: "SBIN",           securityId: "3045",  name: "State Bank of India",      sector: "Banking" },
  { symbol: "BAJFINANCE",     securityId: "317",   name: "Bajaj Finance",            sector: "NBFC" },
  { symbol: "BHARTIARTL",     securityId: "10604", name: "Bharti Airtel",            sector: "Telecom" },
  { symbol: "WIPRO",          securityId: "3787",  name: "Wipro",                    sector: "IT" },
  { symbol: "HCLTECH",        securityId: "7229",  name: "HCL Technologies",         sector: "IT" },
  { symbol: "ASIANPAINT",     securityId: "236",   name: "Asian Paints",             sector: "Chemicals" },
  { symbol: "MARUTI",         securityId: "10999", name: "Maruti Suzuki",            sector: "Auto" },
  { symbol: "SUNPHARMA",      securityId: "3351",  name: "Sun Pharmaceutical",       sector: "Pharma" },
  { symbol: "TATAMOTORS",     securityId: "3456",  name: "Tata Motors",              sector: "Auto" },
  { symbol: "TATASTEEL",      securityId: "3499",  name: "Tata Steel",               sector: "Metals" },
  { symbol: "NTPC",           securityId: "11630", name: "NTPC",                     sector: "Power" },
  { symbol: "POWERGRID",      securityId: "14977", name: "Power Grid Corp",          sector: "Power" },
  { symbol: "ONGC",           securityId: "2475",  name: "ONGC",                     sector: "Energy" },
  { symbol: "INDUSINDBK",     securityId: "5258",  name: "IndusInd Bank",            sector: "Banking" },
  { symbol: "TECHM",          securityId: "13538", name: "Tech Mahindra",            sector: "IT" },
  { symbol: "BAJAJFINSV",     securityId: "16675", name: "Bajaj Finserv",            sector: "NBFC" },
  { symbol: "JSWSTEEL",       securityId: "11723", name: "JSW Steel",                sector: "Metals" },
  { symbol: "GRASIM",         securityId: "1232",  name: "Grasim Industries",        sector: "Cement" },
  { symbol: "ADANIENT",       securityId: "25",    name: "Adani Enterprises",        sector: "Conglomerate" },
  { symbol: "ADANIPORTS",     securityId: "15083", name: "Adani Ports",              sector: "Infrastructure" },
  { symbol: "CIPLA",          securityId: "694",   name: "Cipla",                    sector: "Pharma" },
  { symbol: "DRREDDY",        securityId: "881",   name: "Dr. Reddy's Labs",         sector: "Pharma" },
  { symbol: "DIVISLAB",       securityId: "10940", name: "Divi's Laboratories",      sector: "Pharma" },
  { symbol: "BPCL",           securityId: "526",   name: "BPCL",                     sector: "Energy" },
  { symbol: "COALINDIA",      securityId: "20374", name: "Coal India",               sector: "Mining" },
  { symbol: "HINDALCO",       securityId: "1326",  name: "Hindalco Industries",      sector: "Metals" },
  { symbol: "EICHERMOT",      securityId: "910",   name: "Eicher Motors",            sector: "Auto" },
  { symbol: "UPL",            securityId: "11287", name: "UPL",                      sector: "Agro Chemicals" },
  { symbol: "TATACONSUM",     securityId: "3432",  name: "Tata Consumer Products",   sector: "FMCG" },
  { symbol: "NESTLEIND",      securityId: "17963", name: "Nestle India",             sector: "FMCG" },
  { symbol: "BRITANNIA",      securityId: "547",   name: "Britannia Industries",     sector: "FMCG" },
  { symbol: "HEROMOTOCO",     securityId: "1348",  name: "Hero MotoCorp",            sector: "Auto" },
  { symbol: "APOLLOHOSP",     securityId: "157",   name: "Apollo Hospitals",         sector: "Healthcare" },
  { symbol: "BAJAJ-AUTO",     securityId: "16669", name: "Bajaj Auto",               sector: "Auto" },
  { symbol: "TITAN",          securityId: "3506",  name: "Titan Company",            sector: "Consumer" },
  { symbol: "ULTRACEMCO",     securityId: "11532", name: "UltraTech Cement",         sector: "Cement" },
  { symbol: "SHREECEM",       securityId: "3103",  name: "Shree Cement",             sector: "Cement" },
  { symbol: "HAVELLS",        securityId: "5765",  name: "Havells India",            sector: "Consumer Elec" },
  { symbol: "PIDILITIND",     securityId: "2664",  name: "Pidilite Industries",      sector: "Chemicals" },
  { symbol: "DABUR",          securityId: "772",   name: "Dabur India",              sector: "FMCG" },
  { symbol: "MARICO",         securityId: "4067",  name: "Marico",                   sector: "FMCG" },
  { symbol: "GODREJCP",       securityId: "10099", name: "Godrej Consumer Products", sector: "FMCG" },
  { symbol: "BERGEPAINT",     securityId: "404",   name: "Berger Paints",            sector: "Chemicals" },
  { symbol: "COLPAL",         securityId: "734",   name: "Colgate-Palmolive",        sector: "FMCG" },
  { symbol: "ITC",            securityId: "1660",  name: "ITC",                      sector: "FMCG" },
  { symbol: "VEDL",           securityId: "3063",  name: "Vedanta",                  sector: "Metals" },
  { symbol: "SAIL",           securityId: "2963",  name: "SAIL",                     sector: "Metals" },
  { symbol: "NMDC",           securityId: "15332", name: "NMDC",                     sector: "Mining" },
  { symbol: "RECLTD",         securityId: "14418", name: "REC Limited",              sector: "NBFC" },
  { symbol: "PFC",            securityId: "14299", name: "Power Finance Corp",       sector: "NBFC" },
  { symbol: "CANBK",          securityId: "10794", name: "Canara Bank",              sector: "Banking" },
  { symbol: "BANKBARODA",     securityId: "1152",  name: "Bank of Baroda",           sector: "Banking" },
  { symbol: "PNB",            securityId: "2730",  name: "Punjab National Bank",     sector: "Banking" },
  { symbol: "FEDERALBNK",     securityId: "1023",  name: "Federal Bank",             sector: "Banking" },
  { symbol: "IDFCFIRSTB",     securityId: "14366", name: "IDFC First Bank",          sector: "Banking" },
  { symbol: "BANDHANBNK",     securityId: "2263",  name: "Bandhan Bank",             sector: "Banking" },
  { symbol: "RBLBANK",        securityId: "4708",  name: "RBL Bank",                 sector: "Banking" },
  { symbol: "AUBANK",         securityId: "21238", name: "AU Small Finance Bank",    sector: "Banking" },
  { symbol: "CHOLAFIN",       securityId: "685",   name: "Cholamandalam Finance",    sector: "NBFC" },
  { symbol: "MUTHOOTFIN",     securityId: "18143", name: "Muthoot Finance",          sector: "NBFC" },
  { symbol: "LICHSGFIN",      securityId: "1997",  name: "LIC Housing Finance",      sector: "NBFC" },
  { symbol: "SBICARD",        securityId: "21856", name: "SBI Cards",                sector: "NBFC" },
  { symbol: "HDFCLIFE",       securityId: "119",   name: "HDFC Life Insurance",      sector: "Insurance" },
  { symbol: "SBILIFE",        securityId: "21808", name: "SBI Life Insurance",       sector: "Insurance" },
  { symbol: "ICICIPRULI",     securityId: "21183", name: "ICICI Prudential Life",    sector: "Insurance" },
  { symbol: "GICRE",          securityId: "21614", name: "GIC Re",                   sector: "Insurance" },
  { symbol: "ICICIGI",        securityId: "21196", name: "ICICI Lombard",            sector: "Insurance" },
  { symbol: "M&M",            securityId: "2031",  name: "Mahindra & Mahindra",      sector: "Auto" },
  { symbol: "ASHOKLEY",       securityId: "212",   name: "Ashok Leyland",            sector: "Auto" },
  { symbol: "MOTHERSON",      securityId: "4204",  name: "Samvardhana Motherson",    sector: "Auto Ancillary" },
  { symbol: "BOSCHLTD",       securityId: "467",   name: "Bosch",                    sector: "Auto Ancillary" },
  { symbol: "BALKRISIND",     securityId: "335",   name: "Balkrishna Industries",    sector: "Auto Ancillary" },
  { symbol: "EXIDEIND",       securityId: "954",   name: "Exide Industries",         sector: "Auto Ancillary" },
  { symbol: "MHRIL",          securityId: "2250",  name: "MHR Investment",           sector: "Consumer" },
  { symbol: "TATAPOWER",      securityId: "3426",  name: "Tata Power",               sector: "Power" },
  { symbol: "ADANIGREEN",     securityId: "21514", name: "Adani Green Energy",       sector: "Power" },
  { symbol: "ADANITRANS",     securityId: "21757", name: "Adani Transmission",       sector: "Power" },
  { symbol: "TORNTPOWER",     securityId: "3533",  name: "Torrent Power",            sector: "Power" },
  { symbol: "CESC",           securityId: "660",   name: "CESC",                     sector: "Power" },
  { symbol: "IGL",            securityId: "10633", name: "Indraprastha Gas",         sector: "Energy" },
  { symbol: "MGL",            securityId: "19234", name: "Mahanagar Gas",            sector: "Energy" },
  { symbol: "GUJGASLTD",      securityId: "21141", name: "Gujarat Gas",              sector: "Energy" },
  { symbol: "IOC",            securityId: "1624",  name: "Indian Oil Corporation",   sector: "Energy" },
  { symbol: "HINDPETRO",      securityId: "1406",  name: "HPCL",                     sector: "Energy" },
  { symbol: "CASTROLIND",     securityId: "633",   name: "Castrol India",            sector: "Energy" },
  { symbol: "ZOMATO",         securityId: "21866", name: "Zomato",                   sector: "Consumer Tech" },
  { symbol: "NYKAA",          securityId: "21925", name: "Nykaa",                    sector: "Consumer Tech" },
  { symbol: "PAYTM",          securityId: "21880", name: "Paytm",                    sector: "Fintech" },
  { symbol: "POLICYBZR",      securityId: "21942", name: "PB Fintech",               sector: "Fintech" },
  { symbol: "DELHIVERY",      securityId: "26000", name: "Delhivery",                sector: "Logistics" },
  { symbol: "NAUKRI",         securityId: "13751", name: "Info Edge (Naukri)",       sector: "Consumer Tech" },
  { symbol: "JUSTDIAL",       securityId: "18749", name: "Just Dial",                sector: "Consumer Tech" },
  { symbol: "IRCTC",          securityId: "21750", name: "IRCTC",                    sector: "Consumer" },
  { symbol: "IRFC",           securityId: "21825", name: "Indian Railway Finance",   sector: "NBFC" },
  { symbol: "HAL",            securityId: "10455", name: "HAL",                      sector: "Defence" },
  { symbol: "BEL",            securityId: "383",   name: "Bharat Electronics",       sector: "Defence" },
  { symbol: "BHEL",           securityId: "438",   name: "BHEL",                     sector: "Capital Goods" },
  { symbol: "ABB",            securityId: "13",    name: "ABB India",                sector: "Capital Goods" },
  { symbol: "SIEMENS",        securityId: "3150",  name: "Siemens",                  sector: "Capital Goods" },
  { symbol: "CUMMINSIND",     securityId: "771",   name: "Cummins India",            sector: "Capital Goods" },
  { symbol: "THERMAX",        securityId: "3518",  name: "Thermax",                  sector: "Capital Goods" },
  { symbol: "AIAENG",         securityId: "13",    name: "AIA Engineering",          sector: "Capital Goods" },
  { symbol: "SOLARINDS",      securityId: "3203",  name: "Solar Industries",         sector: "Defence" },
  { symbol: "DIXON",          securityId: "20642", name: "Dixon Technologies",       sector: "Consumer Elec" },
  { symbol: "VOLTAS",         securityId: "3718",  name: "Voltas",                   sector: "Consumer Elec" },
  { symbol: "WHIRLPOOL",      securityId: "3759",  name: "Whirlpool",                sector: "Consumer Elec" },
  { symbol: "BLUEDART",       securityId: "460",   name: "Blue Dart Express",        sector: "Logistics" },
  { symbol: "CONCOR",         securityId: "12025", name: "Container Corp",           sector: "Logistics" },
  { symbol: "GLAND",          securityId: "21901", name: "Gland Pharma",             sector: "Pharma" },
  { symbol: "ALKEM",          securityId: "19351", name: "Alkem Laboratories",       sector: "Pharma" },
  { symbol: "TORNTPHARM",     securityId: "3526",  name: "Torrent Pharma",           sector: "Pharma" },
  { symbol: "LUPIN",          securityId: "10440", name: "Lupin",                    sector: "Pharma" },
  { symbol: "AUROPHARMA",     securityId: "275",   name: "Aurobindo Pharma",         sector: "Pharma" },
  { symbol: "BIOCON",         securityId: "11373", name: "Biocon",                   sector: "Pharma" },
  { symbol: "ABBOTINDIA",     securityId: "14",    name: "Abbott India",             sector: "Pharma" },
  { symbol: "PFIZER",         securityId: "2622",  name: "Pfizer",                   sector: "Pharma" },
  { symbol: "ZYDUSLIFE",      securityId: "21360", name: "Zydus Lifesciences",       sector: "Pharma" },
  { symbol: "IPCALAB",        securityId: "1633",  name: "IPCA Laboratories",        sector: "Pharma" },
  { symbol: "LALPATHLAB",     securityId: "21614", name: "Dr Lal PathLabs",          sector: "Healthcare" },
  { symbol: "METROPOLIS",     securityId: "21748", name: "Metropolis Healthcare",    sector: "Healthcare" },
  { symbol: "MAXHEALTH",      securityId: "21890", name: "Max Healthcare",           sector: "Healthcare" },
  { symbol: "FORTIS",         securityId: "1087",  name: "Fortis Healthcare",        sector: "Healthcare" },
  { symbol: "MCDOWELL-N",     securityId: "2282",  name: "United Spirits",           sector: "Consumer" },
  { symbol: "RADICO",         securityId: "2659",  name: "Radico Khaitan",           sector: "Consumer" },
  { symbol: "VBL",            securityId: "20192", name: "Varun Beverages",          sector: "Consumer" },
  { symbol: "TRENT",          securityId: "3519",  name: "Trent",                    sector: "Retail" },
  { symbol: "DMART",          securityId: "21608", name: "Avenue Supermarts",        sector: "Retail" },
  { symbol: "PAGEIND",        securityId: "14413", name: "Page Industries",          sector: "Retail" },
  { symbol: "ABFRL",          securityId: "15060", name: "ABFRL",                    sector: "Retail" },
  { symbol: "OBEROIRLTY",     securityId: "20741", name: "Oberoi Realty",            sector: "Real Estate" },
  { symbol: "DLF",            securityId: "14732", name: "DLF",                      sector: "Real Estate" },
  { symbol: "GODREJPROP",     securityId: "17875", name: "Godrej Properties",        sector: "Real Estate" },
  { symbol: "PRESTIGE",       securityId: "13673", name: "Prestige Estates",         sector: "Real Estate" },
  { symbol: "PHOENIXLTD",     securityId: "2664",  name: "Phoenix Mills",            sector: "Real Estate" },
  { symbol: "SOBHA",          securityId: "18287", name: "Sobha",                    sector: "Real Estate" },
  { symbol: "MFSL",           securityId: "2268",  name: "Max Financial Services",   sector: "Insurance" },
  { symbol: "CHOLAHLDNG",     securityId: "679",   name: "Cholamandalam Holdings",   sector: "NBFC" },
  { symbol: "MANAPPURAM",     securityId: "19061", name: "Manappuram Finance",       sector: "NBFC" },
  { symbol: "SHRIRAMFIN",     securityId: "3251",  name: "Shriram Finance",          sector: "NBFC" },
  { symbol: "M&MFIN",         securityId: "2036",  name: "M&M Financial Services",   sector: "NBFC" },
  { symbol: "SUNDARMFIN",     securityId: "3324",  name: "Sundaram Finance",         sector: "NBFC" },
  { symbol: "L&TFH",          securityId: "22592", name: "L&T Finance",              sector: "NBFC" },
  { symbol: "PIRAMALENT",     securityId: "14592", name: "Piramal Enterprises",      sector: "NBFC" },
  { symbol: "ANGELONE",       securityId: "21554", name: "Angel One",                sector: "Broking" },
  { symbol: "360ONE",         securityId: "21814", name: "360 ONE WAM",              sector: "Wealth Mgmt" },
  { symbol: "NUVAMA",         securityId: "22918", name: "Nuvama Wealth",            sector: "Wealth Mgmt" },
  { symbol: "KFINTECH",       securityId: "22924", name: "KFin Technologies",        sector: "Fintech" },
  { symbol: "CAMS",           securityId: "21833", name: "CAMS",                     sector: "Fintech" },
  { symbol: "BSE",            securityId: "14149", name: "BSE",                      sector: "Exchange" },
  { symbol: "MCX",            securityId: "19234", name: "MCX",                      sector: "Exchange" },
  { symbol: "CDSL",           securityId: "21686", name: "CDSL",                     sector: "Exchange" },
];
